apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - "/bin/bash"
          - "-c"
          - "/bin/echo Hello from Pod $(hostname) at $(date)"
      restartPolicy: Never # values: Never or OnFailure
