apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-parallelism-job
spec:
  parallelism: 10
  completions: 50
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
