apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: appconfig
          secret:
            secretName: app1
      containers:
      - name: myapp
        image: <image-name>
        # passing the envs defined in a secret to a pod.
        envFrom:
        - secretRef:
           name: app1
        # referencing the secret exposed as a volume mount
        volumeMounts:
          - name:  appconfig
            mountPath: "/etc/appconfig"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
