apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: <image-name>
        # defining env variables
        env:
        - name: DATABASE_SERVERNAME
          value: "sql.example.local"
        - name: DATABASE_USERNAME
          value: "test_user"
        - name: DATABASE_PASSWORD
          value: "test_password"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
