apiVersion: v1
kind: Secret
metadata:
  name: pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJtZWx2aW5raW1hdGhpIiwicGFzc3dvcmQiOiJNZWx2aW4wMDAwMTEiLCJlbWFpbCI6Im1lbHZpbmtpbWF0aGk4OEBnbWFpbC5jb20iLCJhdXRoIjoie3tiYXNlNjRfZW5jb2RlZF9hdXRofX0ifX19